name: CI Fuzz

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: grpc.code-intelligence.com:443
  WEB_APP_ADDRESS: https://app.code-intelligence.com
  CHECKOUT_DIR: checkout-dir/


jobs:
  fuzz_tests:
    runs-on: ubuntu-latest
    container: cifuzz/builders:maven
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.CHECKOUT_DIR }}
      - id: install-build-tools
        name: Install Fuzzer Build Tools
        uses: CodeIntelligenceTesting/github-actions/install-fuzzer-builder@master
      - id: build-fuzzers
        name: Build Fuzzers
        run: ci-fuzz/bin/ci-build fuzzers --directory=$GITHUB_WORKSPACE/$CHECKOUT_DIR/ --git_commit_sha=$GITHUB_SHA --git_branch=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
        shell: "bash"
      - id: start-fuzzing
        name: Start Fuzzing
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          fuzzing_artifact: ${{ env.CHECKOUT_DIR }}/fuzzing-artifacts.tar.gz
          checkout_directory: ${{ env.CHECKOUT_DIR }}
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
          timeout: 1200
      - id: save-results
        name: Save Fuzz Test Results
        uses: CodeIntelligenceTesting/github-actions/save-results@v3
        if: ${{ success() || failure() }}
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: upload-artifact
        uses: actions/upload-artifact@v2
        if: ${{ (success() || failure()) }}
        with:
          name: ci_fuzz_results
          path: | 
            findings.json
            coverage.json
            web_app_address.txt
